from django.contrib import admin
from prottox.models import *

admin.site.register(Toxin)
admin.site.register(Target)
admin.site.register(Target_organism_name)
admin.site.register(Toxin_research)
admin.site.register(Publication)
admin.site.register(Author)
admin.site.register(Larvae_stage)
admin.site.register(Toxin_distribution)
admin.site.register(Toxin_source)
admin.site.register(Toxin_form)
admin.site.register(Toxin_isolation_source)
admin.site.register(Toxin_expression_host)
admin.site.register(Measurement)
admin.site.register(Bioassay_type)
admin.site.register(Result)
admin.site.register(Toxin_quantity)
admin.site.register(Protein_type)
admin.site.register(Family_rank_1)
admin.site.register(Family_rank_2)
admin.site.register(Family_rank_3)
admin.site.register(Family_rank_4)
