from django.contrib import admin
from prottox.models import *

admin.site.register(Active_factor)
admin.site.register(Target)
admin.site.register(Target_organism_name)
admin.site.register(Toxin_research)
admin.site.register(Publication)
admin.site.register(Author)
admin.site.register(Larvae_stage)
admin.site.register(Toxin_distribution)
admin.site.register(Factor_source)
admin.site.register(Factor_form)
admin.site.register(Factor_isolation_source)
admin.site.register(Factor_expression_host)
admin.site.register(Measurement)
admin.site.register(Bioassay_type)
admin.site.register(Result)
admin.site.register(Toxin_quantity)
admin.site.register(Taxonomy)
